import { describe, expect, it } from 'vitest'
import { emptyState } from '../data/emptyState'
import { buildReport } from './reports'
import type { FleetState } from '../types'

function stateWithData():FleetState{return {...structuredClone(emptyState),vehicles:[{id:'v1',plate:'1234ABC',category:'Furgoneta',brand:'Ford',model:'Transit',year:2022,dailyRate:40,weeklyRate:250,monthlyRate:700,includedKmPerDay:125,extraKmRate:.15,status:'disponible',notes:''}],customers:[{id:'c1',name:'Ana',email:'',phone:'',dni:'',rentals:1}],rentals:[{id:'r1',vehicleId:'v1',customerId:'c1',startDate:'2026-05-01',agreedPrice:600,pricePeriod:'mes',expectedKilometers:0,status:'activo',notes:''}],payments:[{id:'p1',rentalId:'r1',dueDate:'2026-06-01',paidDate:'2026-06-02',amount:600,status:'pagado',notes:''},{id:'p2',rentalId:'r1',dueDate:'2026-06-20',amount:200,status:'pendiente',notes:''},{id:'p3',rentalId:'r1',dueDate:'2026-05-01',amount:100,status:'pendiente',notes:''}],maintenance:[{id:'m1',vehicleId:'v1',type:'Reparación motor',date:'2026-06-04',cost:120,status:'completado',notes:''}],documents:[{id:'d1',vehicleId:'v1',type:'ITV',expiryDate:'2026-06-20',cost:50,paymentStatus:'pagado',paidDate:'2026-06-05',notes:''}],taxes:[{id:'t1',vehicleId:'v1',concept:'IVTM',dueDate:'2026-06-08',amount:80,status:'pagado',paidDate:'2026-06-08',notes:''}]}}

describe('buildReport',()=>{
  it('calcula ingresos, gastos, atrasos y beneficio sin duplicar movimientos',()=>{const report=buildReport(stateWithData(),'2026-06-13');expect(report.summary.totalPaid).toBe(600);expect(report.summary.monthIncome).toBe(600);expect(report.summary.monthExpenses).toBe(250);expect(report.summary.monthProfit).toBe(350);expect(report.summary.pending).toBe(200);expect(report.summary.overdue).toBe(100);expect(report.movements).toHaveLength(6);expect(report.monthly.find(item=>item.month==='2026-06')).toMatchObject({paid:600,pending:200,expenses:250,profit:350})})
  it('separa las categorías de gasto registradas',()=>{const report=buildReport(stateWithData(),'2026-06-13');expect(report.categories).toEqual(expect.arrayContaining([{category:'Reparaciones',total:120},{category:'ITV',total:50},{category:'Impuestos',total:80}]))})
  it('muestra informes cuando solo existe un pago pendiente',()=>{const state=stateWithData();state.payments=state.payments.slice(1,2);state.maintenance=[];state.documents=[];state.taxes=[];const report=buildReport(state,'2026-06-13');expect(report.hasEconomicData).toBe(true);expect(report.summary.totalPending).toBe(200);expect(report.summary.totalPaid).toBe(0);expect(report.monthly).toEqual([expect.objectContaining({month:'2026-06',pending:200})])})
  it('respeta un pago marcado manualmente como atrasado',()=>{const state=stateWithData();state.payments=[{id:'late',rentalId:'r1',dueDate:'2026-07-01',amount:90,status:'atrasado',notes:''}];state.maintenance=[];state.documents=[];state.taxes=[];const report=buildReport(state,'2026-06-13');expect(report.summary.totalOverdue).toBe(90);expect(report.summary.totalPending).toBe(0)})
  it('usa el precio del alquiler como previsión solo si no tiene pagos asociados',()=>{const state=stateWithData();state.payments=[];state.maintenance=[];state.documents=[];state.taxes=[];const report=buildReport(state,'2026-06-13');expect(report.hasEconomicData).toBe(true);expect(report.summary.totalOverdue).toBe(600);expect(report.movements).toHaveLength(1);expect(report.movements[0].id).toBe('rental-r1')})
  it('no inventa series cuando el estado está vacío',()=>{const report=buildReport(structuredClone(emptyState),'2026-06-13');expect(report.hasEconomicData).toBe(false);expect(report.monthly).toEqual([]);expect(report.categories).toEqual([]);expect(report.movements).toEqual([])})
})
