import { CalendarClock, Car, CircleAlert, CreditCard, Plus, TrendingUp, Users, type LucideIcon } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Badge, EmptyState, PageHeader, StatCard } from '../components/ui'
import { useFleet } from '../store/FleetContext'
import { date, euro } from '../lib/format'
import { daysUntil, effectivePaymentStatus, isPaymentAlert } from '../lib/payments'
import { getGreeting } from '../lib/greeting'

export default function DashboardPage() {
  const {state,toggleTask,markPaymentPaid}=useFleet(); const available=state.vehicles.filter(v=>v.status==='disponible').length; const active=state.rentals.filter(r=>r.status==='activo').length
  const pending=state.payments.filter(p=>effectivePaymentStatus(p)!=='pagado').reduce((s,p)=>s+p.amount,0), overdue=state.payments.filter(p=>effectivePaymentStatus(p)==='atrasado').reduce((s,p)=>s+p.amount,0)
  const alerts=state.payments.filter(isPaymentAlert).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));const priorityTone={alta:'danger',media:'warning',baja:'info'} as const
  return <div className="fade-up"><PageHeader eyebrow="Centro operativo" title={`${getGreeting()}, ${state.adminSettings.name}`} description="Controla la flota, los alquileres y los próximos cobros desde un solo lugar." action={<Link to="/app/alquileres?new=1" className={`btn-primary ${!state.vehicles.length||!state.customers.length?'pointer-events-none opacity-50':''}`}><Plus size={18}/> Crear alquiler</Link>}/>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Vehículos disponibles" value={`${available} / ${state.vehicles.length}`} detail={state.vehicles.length?'Listos para alquilar':'Añade tu primer vehículo'} icon={Car}/><StatCard label="Alquileres activos" value={String(active)} detail={active?'Contratos en curso':'No hay alquileres activos'} icon={CalendarClock} tone="blue"/><StatCard label="Alertas de pago" value={String(alerts.length)} detail={alerts.length?'Requieren atención':'Cobros al día'} icon={CircleAlert} tone={alerts.length?'red':'green'}/><StatCard label="Dinero atrasado" value={euro.format(overdue)} detail={`${euro.format(pending)} total por cobrar`} icon={TrendingUp} tone={overdue?'red':'green'}/></section>
    {!state.vehicles.length&&<section className="card mt-5 overflow-hidden border-brand-200 bg-gradient-to-r from-brand-50 to-white p-6 sm:p-8"><div className="flex flex-col items-start gap-5 sm:flex-row sm:items-center"><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-brand-500 text-white"><Car/></span><div className="flex-1"><h2 className="font-display text-2xl font-bold">Empieza creando tu flota</h2><p className="mt-2 text-stone-600">Añade el primer coche o furgoneta para activar alquileres, pagos y alertas.</p></div><Link to="/app/flota" className="btn-primary">Añadir primer vehículo</Link></div></section>}
    <section className="card mt-5 p-5 sm:p-6"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-brand-600">Cobros</p><h2 className="mt-1 font-display text-xl font-bold">Alertas de pagos</h2></div><Link to="/app/pagos" className="text-sm font-bold text-brand-600">Ver todos los pagos</Link></div>{alerts.length?<div className="mt-5 grid gap-3">{alerts.slice(0,5).map(p=>{const r=state.rentals.find(x=>x.id===p.rentalId),c=state.customers.find(x=>x.id===r?.customerId),v=state.vehicles.find(x=>x.id===r?.vehicleId),status=effectivePaymentStatus(p),days=daysUntil(p.dueDate);const label=status==='flexible'?'Pago flexible':status==='atrasado'?'Pago atrasado':days===0?'Pago vence hoy':'Pago próximo';return <article key={p.id} className="flex flex-col gap-3 rounded-xl border border-orange-100 bg-brand-50/30 p-4 md:flex-row md:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-bold text-ink">{c?.name}</p><Badge tone={status==='atrasado'?'danger':status==='flexible'?'info':'warning'}>{label}</Badge></div><p className="mt-1 text-sm text-stone-500">{v?.name} · {v?.plate} · {date(p.dueDate)}</p></div><p className="font-display text-lg font-bold">{euro.format(p.amount)}</p>{status!=='pagado'&&<button className="btn-primary" onClick={()=>markPaymentPaid(p.id)}>Marcar como pagado</button>}</article>})}</div>:<EmptyState title="No hay alertas de pago." description="Los pagos próximos, vencidos o flexibles aparecerán aquí."/>}</section>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="card p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-brand-600">Organización</p><h2 className="mt-1 font-display text-xl font-bold">Tareas</h2></div><Link to="/app/tareas" className="text-sm font-bold text-brand-600">Gestionar</Link></div>{state.tasks.length?<div className="mt-5 space-y-2">{state.tasks.slice(0,5).map(task=><label key={task.id} className="flex cursor-pointer items-start gap-3 rounded-xl border border-orange-100 p-3.5 hover:bg-brand-50"><input type="checkbox" checked={task.completed} onChange={()=>toggleTask(task.id)} className="mt-1 size-4 accent-orange-500"/><span className="min-w-0 flex-1"><span className={`block font-semibold ${task.completed?'text-stone-400 line-through':'text-ink'}`}>{task.title}</span><span className="mt-1 block text-xs text-stone-500">{task.category} · {date(task.dueDate)}</span></span><Badge tone={priorityTone[task.priority]}>{task.priority}</Badge></label>)}</div>:<EmptyState title="No hay tareas pendientes." description="Crea tareas para organizar el trabajo del equipo."/>}</section><section className="card p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-brand-600">Resumen</p><h2 className="mt-1 font-display text-xl font-bold">Actividad</h2></div><CreditCard className="text-brand-500"/></div><div className="mt-6 grid grid-cols-2 gap-3"><Mini label="Clientes" value={state.customers.length} icon={Users}/><Mini label="Vehículos" value={state.vehicles.length} icon={Car}/><Mini label="Alquileres" value={state.rentals.length} icon={CalendarClock}/><Mini label="Pagos" value={state.payments.length} icon={CreditCard}/></div></section></div>
  </div>
}
function Mini({label,value,icon:Icon}:{label:string;value:number;icon:LucideIcon}){return <div className="rounded-2xl bg-brand-50 p-4"><Icon className="text-brand-600" size={20}/><p className="mt-4 text-2xl font-bold">{value}</p><p className="text-sm text-stone-500">{label}</p></div>}
