import { useState, type FormEvent } from 'react'
import { AlertTriangle, CheckCircle2, FileCheck2, Gavel, Plus, ReceiptText } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { Badge, ConfirmButton, EmptyState, Modal, PageHeader, StatCard } from '../components/ui'
import { useFleet } from '../store/FleetContext'
import { date, euro, uid } from '../lib/format'
import { daysUntil } from '../lib/payments'
import { vehicleLabel } from '../lib/vehicles'
import type { Document, Fine, VehicleTax } from '../types'

type Editor = { kind:'document'; item:Document } | { kind:'tax'; item:VehicleTax } | { kind:'fine'; item:Fine }

export default function DocumentationPage() {
  const {state,remove}=useFleet(); const [params,setParams]=useSearchParams(); const selected=params.get('vehicle')||'todos'; const [editor,setEditor]=useState<Editor|null>(null)
  const matches=(vehicleId:string)=>selected==='todos'||vehicleId===selected
  const documents=state.documents.filter(item=>matches(item.vehicleId))
  const taxes=state.taxes.filter(item=>matches(item.vehicleId))
  const fines=state.fines.filter(item=>matches(item.vehicleId))
  const docStatus=(item:Document)=>daysUntil(item.expiryDate)<0?'caducado':daysUntil(item.expiryDate)<=30?'próximo':'vigente'
  const blankVehicle=selected==='todos'?state.vehicles[0]?.id||'':selected
  const openDocument=()=>setEditor({kind:'document',item:{id:'',vehicleId:blankVehicle,type:'ITV',expiryDate:'',cost:0,paymentStatus:'pendiente',notes:''}})
  const openTax=()=>setEditor({kind:'tax',item:{id:'',vehicleId:blankVehicle,concept:'Impuesto de circulación',dueDate:'',amount:0,status:'pendiente',notes:''}})
  const openFine=()=>setEditor({kind:'fine',item:{id:'',vehicleId:blankVehicle,infractionDate:'',amount:0,status:'pendiente',concept:'Multa de tráfico',notes:''}})
  return <div className="fade-up"><PageHeader eyebrow="Cumplimiento" title="ITV y documentación" description="Documentos, ITV, impuestos, multas y vencimientos conectados con cada vehículo." action={<select className="field min-w-56" value={selected} onChange={event=>setParams(event.target.value==='todos'?{}:{vehicle:event.target.value})} aria-label="Filtrar por vehículo"><option value="todos">Toda la flota</option>{state.vehicles.map(v=><option key={v.id} value={v.id}>{vehicleLabel(v)} · {v.plate}</option>)}</select>}/>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Documentos vigentes" value={String(documents.filter(item=>docStatus(item)==='vigente').length)} detail="Sin acciones pendientes" icon={CheckCircle2} tone="green"/><StatCard label="Próximos a vencer" value={String(documents.filter(item=>docStatus(item)==='próximo').length)} detail="Aviso en 30 días" icon={FileCheck2}/><StatCard label="Caducados" value={String(documents.filter(item=>docStatus(item)==='caducado').length)} detail="Requieren atención" icon={AlertTriangle} tone="red"/><StatCard label="Gastos registrados" value={euro.format(documents.reduce((sum,item)=>sum+(item.cost||0),0)+taxes.filter(item=>item.status==='pagado').reduce((sum,item)=>sum+item.amount,0)+fines.reduce((sum,item)=>sum+item.amount,0))} detail="Documentación, impuestos y multas" icon={ReceiptText} tone="blue"/></section>
    {!state.vehicles.length?<div className="card mt-5"><EmptyState title="Añade un vehículo primero." description="La documentación y los gastos siempre quedan asociados a una matrícula."/></div>:<div className="mt-5 grid gap-5 xl:grid-cols-2">
      <Panel title="Documentación e ITV" icon={FileCheck2} onAdd={openDocument}>{documents.length?documents.map(item=>{const vehicle=state.vehicles.find(v=>v.id===item.vehicleId),status=docStatus(item);return <Record key={item.id} title={item.type} subtitle={`${vehicleLabel(vehicle)} · ${vehicle?.plate}`} meta={`Vence ${date(item.expiryDate)}${item.cost?` · ${euro.format(item.cost)}`:''}`} badge={<Badge tone={status==='vigente'?'success':status==='próximo'?'warning':'danger'}>{status}</Badge>} onEdit={()=>setEditor({kind:'document',item})} onDelete={()=>remove('documents',item.id)}/>}):<SmallEmpty text="No hay documentos registrados."/>}</Panel>
      <Panel title="Impuestos" icon={ReceiptText} onAdd={openTax}>{taxes.length?taxes.map(item=>{const vehicle=state.vehicles.find(v=>v.id===item.vehicleId);return <Record key={item.id} title={item.concept} subtitle={`${vehicleLabel(vehicle)} · ${vehicle?.plate}`} meta={`${date(item.dueDate)} · ${euro.format(item.amount)}`} badge={<Badge tone={item.status==='pagado'?'success':daysUntil(item.dueDate)<0?'danger':'warning'}>{item.status}</Badge>} onEdit={()=>setEditor({kind:'tax',item})} onDelete={()=>remove('taxes',item.id)}/>}):<SmallEmpty text="No hay impuestos registrados."/>}</Panel>
      <Panel title="Multas" icon={Gavel} onAdd={openFine}>{fines.length?fines.map(item=>{const vehicle=state.vehicles.find(v=>v.id===item.vehicleId),customer=state.customers.find(c=>c.id===item.customerId);return <Record key={item.id} title={item.concept} subtitle={`${vehicleLabel(vehicle)} · ${customer?.name||'Sin cliente vinculado'}`} meta={`${date(item.infractionDate)} · ${euro.format(item.amount)}`} badge={<Badge tone={item.status==='pagada'||item.status==='archivada'?'success':item.status==='reclamada'?'info':'warning'}>{item.status}</Badge>} onEdit={()=>setEditor({kind:'fine',item})} onDelete={()=>remove('fines',item.id)}/>}):<SmallEmpty text="No hay multas registradas."/>}</Panel>
    </div>}
    {editor&&(editor.kind==='fine'?<FineModal item={editor.item} onClose={()=>setEditor(null)}/>:<EditorModal editor={editor} onClose={()=>setEditor(null)}/>)} 
  </div>
}

function EditorModal({editor,onClose}:{editor:Editor;onClose:()=>void}){const {state,upsert}=useFleet();const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);if(editor.kind==='document'){const paymentStatus=String(f.get('status')) as Document['paymentStatus'];upsert('documents',{id:editor.item.id||uid('d'),vehicleId:String(f.get('vehicleId')),type:String(f.get('type')).trim(),expiryDate:String(f.get('date')),cost:Number(f.get('amount'))||0,paymentStatus,paidDate:paymentStatus==='pagado'?editor.item.paidDate||new Date().toISOString().slice(0,10):undefined,notes:String(f.get('notes')).trim()})}if(editor.kind==='tax')upsert('taxes',{id:editor.item.id||uid('tax'),vehicleId:String(f.get('vehicleId')),concept:String(f.get('type')).trim(),dueDate:String(f.get('date')),amount:Number(f.get('amount'))||0,status:String(f.get('status')) as VehicleTax['status'],paidDate:String(f.get('status'))==='pagado'?new Date().toISOString().slice(0,10):undefined,notes:String(f.get('notes')).trim()});onClose()};const isDocument=editor.kind==='document';const title=isDocument?'documento':'impuesto';const values=isDocument?{type:editor.item.type,date:editor.item.expiryDate,amount:editor.item.cost||0,status:editor.item.paymentStatus||'pendiente'}:{type:editor.item.concept,date:editor.item.dueDate,amount:editor.item.amount,status:editor.item.status};return <Modal title={`${editor.item.id?'Editar':'Añadir'} ${title}`} onClose={onClose}><form className="grid gap-4 sm:grid-cols-2" onSubmit={save}><label><span className="label">Vehículo</span><select className="field" name="vehicleId" defaultValue={editor.item.vehicleId} required>{state.vehicles.map(v=><option key={v.id} value={v.id}>{vehicleLabel(v)} · {v.plate}</option>)}</select></label><label><span className="label">{isDocument?'Tipo de documento':'Concepto'}</span><input className="field" name="type" defaultValue={values.type} required/></label><label><span className="label">{isDocument?'Fecha de vencimiento':'Fecha'}</span><input className="field" name="date" type="date" defaultValue={values.date} required/></label><label><span className="label">Importe (€)</span><input className="field" name="amount" type="number" step="0.01" min="0" defaultValue={values.amount}/></label><label><span className="label">Estado</span><select className="field" name="status" defaultValue={values.status}><option value="pendiente">Pendiente</option><option value="pagado">Pagado</option></select></label><label className="sm:col-span-2"><span className="label">Notas</span><textarea className="field min-h-24" name="notes" defaultValue={editor.item.notes}/></label><div className="flex gap-3 sm:col-span-2 sm:justify-end"><button type="button" className="btn-secondary" onClick={onClose}>Cancelar</button><button className="btn-primary">Guardar</button></div></form></Modal>}
function Panel({title,icon:Icon,onAdd,children}:{title:string;icon:typeof FileCheck2;onAdd:()=>void;children:React.ReactNode}){return <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-orange-100 p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-600"><Icon size={19}/></span><h2 className="font-display font-bold">{title}</h2></div><button className="icon-btn" onClick={onAdd} aria-label={`Añadir en ${title}`}><Plus size={18}/></button></div><div className="divide-y divide-orange-100 p-2">{children}</div></section>}
function Record({title,subtitle,meta,badge,onEdit,onDelete}:{title:string;subtitle:string;meta:string;badge:React.ReactNode;onEdit:()=>void;onDelete:()=>void}){return <article className="rounded-xl p-3 hover:bg-brand-50"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-bold text-ink">{title}</p><p className="truncate text-xs text-stone-500">{subtitle}</p></div>{badge}</div><div className="mt-3 flex items-center justify-between gap-3"><p className="text-sm text-stone-600">{meta}</p><div className="flex items-center gap-3"><button className="text-sm font-bold text-brand-600" onClick={onEdit}>Editar</button><ConfirmButton onConfirm={onDelete}/></div></div></article>}
function SmallEmpty({text}:{text:string}){return <p className="p-8 text-center text-sm text-stone-500">{text}</p>}
function FineModal({item,onClose}:{item:Fine;onClose:()=>void}){const {state,upsert}=useFleet();const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget),vehicleId=String(f.get('vehicleId')),infractionDate=String(f.get('date'));const rental=state.rentals.find(r=>r.vehicleId===vehicleId&&r.startDate<=infractionDate&&(!r.endDate||r.endDate>=infractionDate));upsert('fines',{id:item.id||uid('fine'),vehicleId,customerId:rental?.customerId,rentalId:rental?.id,infractionDate,amount:Number(f.get('amount'))||0,status:String(f.get('status')) as Fine['status'],concept:String(f.get('concept')).trim(),notes:String(f.get('notes')).trim()});onClose()};return <Modal title={item.id?'Editar multa':'Añadir multa'} onClose={onClose}><form className="grid gap-4 sm:grid-cols-2" onSubmit={save}><label><span className="label">Vehículo</span><select className="field" name="vehicleId" defaultValue={item.vehicleId} required>{state.vehicles.map(v=><option key={v.id} value={v.id}>{vehicleLabel(v)} · {v.plate}</option>)}</select></label><label><span className="label">Fecha de infracción</span><input className="field" name="date" type="date" defaultValue={item.infractionDate} required/></label><label><span className="label">Concepto</span><input className="field" name="concept" defaultValue={item.concept} required/></label><label><span className="label">Importe (€)</span><input className="field" name="amount" type="number" min="0" step="0.01" defaultValue={item.amount}/></label><label><span className="label">Estado</span><select className="field" name="status" defaultValue={item.status}>{['pendiente','pagada','reclamada','cargada al cliente','archivada'].map(value=><option key={value}>{value}</option>)}</select></label><p className="self-end rounded-xl bg-brand-50 p-3 text-sm text-stone-600">Se vinculará al cliente que tenía el vehículo alquilado en esa fecha.</p><label className="sm:col-span-2"><span className="label">Notas</span><textarea className="field min-h-24" name="notes" defaultValue={item.notes}/></label><div className="flex gap-3 sm:col-span-2 sm:justify-end"><button type="button" className="btn-secondary" onClick={onClose}>Cancelar</button><button className="btn-primary">Guardar multa</button></div></form></Modal>}
