import { useDeferredValue, useMemo, useState, type FormEvent } from 'react'
import { Car, FileCheck2, ImagePlus, Pencil, Plus, Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Badge, ConfirmButton, EmptyState, Modal, PageHeader } from '../components/ui'
import { useFleet } from '../store/FleetContext'
import { euro, uid } from '../lib/format'
import { vehicleLabel } from '../lib/vehicles'
import type { Vehicle, VehicleStatus } from '../types'

const blank:Vehicle={id:'',name:'',plate:'',brand:'',model:'',year:new Date().getFullYear(),category:'Coche utilitario',status:'disponible',dailyRate:20,weeklyRate:126,monthlyRate:600,includedKmPerDay:125,extraKmRate:.15,image:'',notes:''}
const tones={disponible:'success',alquilado:'info',mantenimiento:'danger',reservado:'warning'} as const

export default function FleetPage(){
  const {state,upsert,remove}=useFleet(); const [query,setQuery]=useState(''); const deferred=useDeferredValue(query); const [status,setStatus]=useState('todos'); const [editing,setEditing]=useState<Vehicle|null>(null); const [uploadedImage,setUploadedImage]=useState(''); const [error,setError]=useState('')
  const rows=useMemo(()=>state.vehicles.filter(v=>(status==='todos'||v.status===status)&&`${vehicleLabel(v)} ${v.plate} ${v.brand} ${v.model} ${v.status}`.toLowerCase().includes(deferred.toLowerCase())),[state.vehicles,status,deferred])
  const open=(vehicle:Vehicle)=>{setError('');setUploadedImage(vehicle.image||'');setEditing(vehicle)}
  const chooseImage=(file?:File)=>{if(!file)return;if(!file.type.startsWith('image/')){setError('Selecciona un archivo de imagen.');return}if(file.size>1_500_000){setError('La imagen debe pesar menos de 1,5 MB.');return}const reader=new FileReader();reader.onload=()=>setUploadedImage(String(reader.result));reader.readAsDataURL(file)}
  const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);const plate=String(f.get('plate')).trim().toUpperCase(),dailyRate=Number(f.get('dailyRate')),weeklyRate=Number(f.get('weeklyRate')),monthlyRate=Number(f.get('monthlyRate'));if(!plate){setError('La matrícula es obligatoria.');return}if([dailyRate,weeklyRate,monthlyRate].some(value=>!Number.isFinite(value)||value<0)){setError('Las tarifas deben ser importes válidos.');return}const brand=String(f.get('brand')).trim(),model=String(f.get('model')).trim();upsert('vehicles',{id:editing?.id||uid('v'),name:`${brand} ${model}`.trim(),plate,brand,model,year:Number(f.get('year'))||new Date().getFullYear(),category:String(f.get('category')),status:String(f.get('status')) as VehicleStatus,dailyRate,weeklyRate,monthlyRate,includedKmPerDay:Number(f.get('includedKmPerDay'))||0,extraKmRate:Number(f.get('extraKmRate'))||0,image:uploadedImage||editing?.image||'',notes:String(f.get('notes')).trim()});setEditing(null);setUploadedImage('')}
  return <div className="fade-up"><PageHeader eyebrow="Operaciones" title="Flota" description="Controla disponibilidad, tarifas y documentación de cada vehículo." action={state.vehicles.length>0?<button className="btn-primary" onClick={()=>open({...blank})}><Plus size={18}/> Añadir vehículo</button>:undefined}/>
    {state.vehicles.length>0&&<div className="mb-5 grid gap-3 sm:grid-cols-[minmax(0,1fr)_220px]"><label className="group relative min-w-0"><span className="sr-only">Buscar vehículo</span><input className="field w-full border-orange-200 pr-11" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar matrícula, marca, modelo o estado"/>{!query&&<Search className="pointer-events-none absolute right-3.5 top-1/2 -translate-y-1/2 text-brand-500 group-focus-within:hidden" size={18}/>}</label><select className="field w-full" value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filtrar por estado"><option value="todos">Todos los estados</option><option value="disponible">Disponible</option><option value="alquilado">Alquilado</option><option value="reservado">Reservado</option><option value="mantenimiento">Mantenimiento</option></select></div>}
    <div className="table-shell">{state.vehicles.length?rows.length?<table className="data-table"><thead><tr><th>Vehículo</th><th>Estado</th><th>Tarifas</th><th>Kilometraje</th><th>Documentación</th><th>Acciones</th></tr></thead><tbody>{rows.map(v=>{const records=state.documents.filter(x=>x.vehicleId===v.id).length+state.maintenance.filter(x=>x.vehicleId===v.id).length+state.taxes.filter(x=>x.vehicleId===v.id).length+state.fines.filter(x=>x.vehicleId===v.id).length;return <tr key={v.id}><td><div className="flex items-center gap-3">{v.image?<img src={v.image} alt={vehicleLabel(v)} className="size-14 rounded-xl object-cover"/>:<span className="grid size-14 place-items-center rounded-xl bg-brand-50 text-brand-600"><Car size={20}/></span>}<div><p className="font-bold">{vehicleLabel(v)}</p><p className="text-xs text-stone-500">{v.plate} · {v.category} · {v.year}</p></div></div></td><td><Badge tone={tones[v.status]}>{v.status}</Badge></td><td className="font-semibold tabular-nums">{euro.format(v.dailyRate)}/día<span className="block text-xs font-normal text-stone-500">{euro.format(v.weeklyRate)}/sem · {euro.format(v.monthlyRate)}/mes</span></td><td>{v.includedKmPerDay} km/día<span className="block text-xs text-stone-500">Extra {euro.format(v.extraKmRate)} + IVA 21%</span></td><td><Link to={`/app/documentacion?vehicle=${v.id}`} className="inline-flex items-center gap-2 font-bold text-brand-600"><FileCheck2 size={17}/>{records} registros</Link></td><td><div className="flex items-center gap-4"><button onClick={()=>open(v)} aria-label={`Editar ${v.plate}`} className="text-stone-500 hover:text-brand-600"><Pencil size={18}/></button><ConfirmButton onConfirm={()=>remove('vehicles',v.id)}/></div></td></tr>})}</tbody></table>:<EmptyState title="No hay vehículos que coincidan." description="Ajusta la búsqueda o cambia el filtro para ver más resultados."/>:<EmptyState title="Todavía no hay vehículos añadidos." description="Añade tu primer vehículo para empezar a gestionar la flota." action={<button className="btn-primary" onClick={()=>open({...blank})}><Plus size={18}/> Añadir vehículo</button>}/>}</div>
    {editing&&<Modal title={editing.id?'Editar vehículo':'Añadir vehículo'} onClose={()=>setEditing(null)}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2">{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700 sm:col-span-2">{error}</p>}<Field label="Matrícula" name="plate" value={editing.plate} required/><label><span className="label">Tipo de vehículo</span><select name="category" className="field" defaultValue={editing.category}>{['Coche utilitario','Furgoneta pequeña','Furgoneta','Moto','SUV','Otro'].map(value=><option key={value}>{value}</option>)}</select></label><Field label="Marca" name="brand" value={editing.brand}/><Field label="Modelo" name="model" value={editing.model}/><Field label="Año" name="year" type="number" value={editing.year}/><label><span className="label">Estado</span><select name="status" className="field" defaultValue={editing.status}>{['disponible','alquilado','reservado','mantenimiento'].map(value=><option key={value}>{value}</option>)}</select></label><Field label="Precio por día (€)" name="dailyRate" type="number" value={editing.dailyRate} required/><Field label="Precio por semana (€)" name="weeklyRate" type="number" value={editing.weeklyRate} required/><Field label="Precio por mes (€)" name="monthlyRate" type="number" value={editing.monthlyRate} required/><Field label="Km incluidos por día" name="includedKmPerDay" type="number" value={editing.includedKmPerDay}/><label><span className="label">Precio por km extra (€ + IVA 21%)</span><input className="field" name="extraKmRate" type="number" step="0.01" defaultValue={editing.extraKmRate}/></label><label className="sm:col-span-2"><span className="label">Imagen del vehículo (opcional)</span><span className="flex flex-col gap-3 rounded-2xl border border-dashed border-orange-200 bg-brand-50/50 p-4 sm:flex-row sm:items-center">{uploadedImage?<img src={uploadedImage} alt="Vista previa" className="size-24 rounded-xl object-cover"/>:<span className="grid size-24 place-items-center rounded-xl bg-white text-brand-500"><ImagePlus size={28}/></span>}<span><input type="file" accept="image/*" className="block max-w-full text-sm file:mr-3 file:rounded-lg file:border-0 file:bg-brand-500 file:px-3 file:py-2 file:font-bold file:text-white" onChange={e=>chooseImage(e.target.files?.[0])}/><span className="mt-2 block text-xs text-stone-500">JPG, PNG o WebP. Máximo 1,5 MB.</span></span></span></label><label className="sm:col-span-2"><span className="label">Notas internas</span><textarea name="notes" className="field min-h-24" defaultValue={editing.notes}/></label><div className="flex gap-3 sm:col-span-2 sm:justify-end"><button type="button" className="btn-secondary" onClick={()=>setEditing(null)}>Cancelar</button><button className="btn-primary">Guardar vehículo</button></div></form></Modal>}
  </div>
}
function Field({label,name,type='text',value,required=false}:{label:string;name:string;type?:string;value:string|number;required?:boolean}){return <label><span className="label">{label}{required&&' *'}</span><input className="field" name={name} type={type} step={type==='number'?'0.01':undefined} defaultValue={value} required={required}/></label>}
