import { useDeferredValue, useMemo, useState, type FormEvent } from 'react'
import { Check, CreditCard, Pencil, Plus, Search } from 'lucide-react'
import { Badge, ConfirmButton, EmptyState, Modal, PageHeader, StatCard } from '../components/ui'
import { useFleet } from '../store/FleetContext'
import { date, euro, uid } from '../lib/format'
import { effectivePaymentStatus } from '../lib/payments'
import { vehicleLabel } from '../lib/vehicles'
import type { Payment, PaymentStatus } from '../types'

const tones={pagado:'success',pendiente:'warning',atrasado:'danger',flexible:'info'} as const
export default function PaymentsPage(){
  const {state,upsert,remove,markPaymentPaid}=useFleet(); const [query,setQuery]=useState(''); const deferred=useDeferredValue(query); const [filter,setFilter]=useState('todos'); const [editing,setEditing]=useState<Payment|null>(null); const [error,setError]=useState('')
  const decorated=useMemo(()=>state.payments.map(payment=>{const rental=state.rentals.find(x=>x.id===payment.rentalId),customer=state.customers.find(x=>x.id===rental?.customerId),vehicle=state.vehicles.find(x=>x.id===rental?.vehicleId);return{payment,rental,customer,vehicle,status:effectivePaymentStatus(payment)}}),[state])
  const rows=useMemo(()=>decorated.filter(x=>(filter==='todos'||x.status===filter)&&`${x.customer?.name} ${vehicleLabel(x.vehicle)} ${x.vehicle?.plate} ${x.payment.dueDate} ${x.status}`.toLowerCase().includes(deferred.toLowerCase())),[decorated,filter,deferred])
  const paid=decorated.filter(x=>x.status==='pagado').reduce((sum,x)=>sum+x.payment.amount,0),pending=decorated.filter(x=>x.status!=='pagado').reduce((sum,x)=>sum+x.payment.amount,0),overdue=decorated.filter(x=>x.status==='atrasado').reduce((sum,x)=>sum+x.payment.amount,0)
  const open=(payment:Payment)=>{setError('');setEditing(payment)}
  const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget),amount=Number(f.get('amount')),dueDate=String(f.get('dueDate')),rentalId=String(f.get('rentalId'));if(!rentalId||!dueDate||amount<=0){setError('Completa el alquiler, la fecha y un importe válido.');return}upsert('payments',{id:editing?.id||uid('p'),rentalId,dueDate,paidDate:String(f.get('status'))==='pagado'?(editing?.paidDate||new Date().toISOString().slice(0,10)):undefined,amount,status:String(f.get('status')) as PaymentStatus,method:String(f.get('method')),notes:String(f.get('notes')).trim()});setEditing(null)}
  const blank=():Payment=>({id:'',rentalId:state.rentals[0]?.id||'',dueDate:new Date().toISOString().slice(0,10),amount:state.rentals[0]?.agreedPrice||0,status:'pendiente',method:'',notes:''})
  return <div className="fade-up"><PageHeader eyebrow="Cobros" title="Pagos" description="Controla los importes pendientes, cobrados y atrasados." action={state.payments.length>0?<button className="btn-primary" disabled={!state.rentals.length} onClick={()=>open(blank())}><Plus size={18}/> Registrar pago</button>:undefined}/>
    <section className="grid gap-4 sm:grid-cols-3"><StatCard label="Cobrado" value={euro.format(paid)} detail="Pagos registrados" icon={Check} tone="green"/><StatCard label="Por cobrar" value={euro.format(pending)} detail="Pendiente, atrasado o flexible" icon={CreditCard}/><StatCard label="Dinero atrasado" value={euro.format(overdue)} detail={`${decorated.filter(x=>x.status==='atrasado').length} pagos requieren seguimiento`} icon={CreditCard} tone="red"/></section>
    {state.payments.length>0&&<><div className="mt-5 flex flex-wrap gap-2">{['todos','pendiente','atrasado','flexible','pagado'].map(value=><button key={value} className={`min-h-10 rounded-xl px-4 text-sm font-bold capitalize ${filter===value?'bg-brand-500 text-white':'border border-orange-100 bg-white text-stone-600'}`} onClick={()=>setFilter(value)}>{value}</button>)}</div><label className="group relative my-4 block max-w-2xl"><span className="sr-only">Buscar pagos</span><input className="field pr-11" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente, vehículo, fecha o estado"/>{!query&&<Search className="pointer-events-none absolute right-3.5 top-1/2 -translate-y-1/2 text-brand-500 group-focus-within:hidden" size={18}/>}</label></>}
    <div className="table-shell mt-5">{state.payments.length?rows.length?<table className="data-table"><thead><tr><th>Cliente y vehículo</th><th>Fecha</th><th>Estado</th><th>Método</th><th>Importe</th><th>Acciones</th></tr></thead><tbody>{rows.map(({payment,customer,vehicle,status})=><tr key={payment.id}><td><p className="font-bold">{customer?.name||'Cliente no disponible'}</p><p className="text-xs text-stone-500">{vehicleLabel(vehicle)} · {vehicle?.plate}</p></td><td>{date(payment.dueDate)}{payment.paidDate&&<span className="block text-xs text-stone-500">Pagado: {date(payment.paidDate)}</span>}</td><td><Badge tone={tones[status]}>{status}</Badge></td><td>{payment.method||'Sin indicar'}</td><td className="font-bold">{euro.format(payment.amount)}</td><td><div className="flex items-center gap-3">{status!=='pagado'&&<button className="btn-primary min-h-9 px-3 py-1 text-xs" onClick={()=>markPaymentPaid(payment.id)}><Check size={15}/> Pagado</button>}<button onClick={()=>open(payment)} aria-label="Editar pago" className="text-stone-500 hover:text-brand-600"><Pencil size={18}/></button><ConfirmButton onConfirm={()=>remove('payments',payment.id)}/></div></td></tr>)}</tbody></table>:<EmptyState title="No hay pagos que coincidan." description="Ajusta la búsqueda o cambia el filtro para ver más resultados."/>:<EmptyState title="No hay pagos registrados." description="Los pagos creados desde alquileres aparecerán aquí." action={state.rentals.length?<button className="btn-primary" onClick={()=>open(blank())}><Plus size={18}/> Registrar pago</button>:undefined}/>}</div>
    {editing&&<Modal title={editing.id?'Editar pago':'Registrar pago'} onClose={()=>setEditing(null)}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2">{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700 sm:col-span-2">{error}</p>}<label className="sm:col-span-2"><span className="label">Alquiler *</span><select className="field" name="rentalId" defaultValue={editing.rentalId} required>{state.rentals.map(r=>{const c=state.customers.find(x=>x.id===r.customerId),v=state.vehicles.find(x=>x.id===r.vehicleId);return <option key={r.id} value={r.id}>{c?.name} · {vehicleLabel(v)} ({v?.plate})</option>})}</select></label><Field label="Fecha de pago" name="dueDate" type="date" value={editing.dueDate}/><Field label="Importe (€)" name="amount" type="number" value={editing.amount}/><label><span className="label">Estado</span><select className="field" name="status" defaultValue={editing.status}>{['pendiente','pagado','atrasado','flexible'].map(value=><option key={value}>{value}</option>)}</select></label><label><span className="label">Método de pago</span><select className="field" name="method" defaultValue={editing.method}><option value="">Sin indicar</option><option>Transferencia</option><option>Efectivo</option><option>Bizum</option><option>Domiciliación</option><option>Tarjeta</option></select></label><label className="sm:col-span-2"><span className="label">Notas</span><textarea className="field min-h-24" name="notes" defaultValue={editing.notes}/></label><div className="flex gap-3 sm:col-span-2 sm:justify-end"><button type="button" className="btn-secondary" onClick={()=>setEditing(null)}>Cancelar</button><button className="btn-primary">Guardar pago</button></div></form></Modal>}
  </div>
}
function Field({label,name,type,value}:{label:string;name:string;type:string;value:string|number}){return <label><span className="label">{label} *</span><input className="field" name={name} type={type} min={type==='number'?'0.01':undefined} step={type==='number'?'0.01':undefined} defaultValue={value} required/></label>}
