import { useDeferredValue, useMemo, useState, type FormEvent } from 'react'
import { CalendarRange, CheckCircle2, Pencil, Plus, Search } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { Badge, ConfirmButton, EmptyState, Modal, PageHeader } from '../components/ui'
import { useFleet } from '../store/FleetContext'
import { date, euro, uid } from '../lib/format'
import { vehicleLabel } from '../lib/vehicles'
import type { PricePeriod, Rental, RentalStatus } from '../types'

const tones={activo:'success',pendiente:'warning',cancelado:'danger',finalizado:'neutral'} as const
const periods:Record<PricePeriod,string>={dia:'día',semana:'semana',mes:'mes',otro:'otro periodo'}

export default function RentalsPage(){
  const {state,upsert,remove}=useFleet(); const [params]=useSearchParams(); const [filter,setFilter]=useState('todos'); const [query,setQuery]=useState(''); const deferred=useDeferredValue(query); const [error,setError]=useState('')
  const blank=():Rental=>({id:'',vehicleId:state.vehicles[0]?.id||'',customerId:state.customers[0]?.id||'',startDate:new Date().toISOString().slice(0,10),endDate:'',agreedPrice:state.vehicles[0]?.monthlyRate||0,pricePeriod:'mes',expectedKilometers:0,nextPaymentDate:'',status:'activo',notes:''})
  const [editing,setEditing]=useState<Rental|null>(()=>params.get('new')==='1'?blank():null)
  const rows=useMemo(()=>state.rentals.filter(r=>{const c=state.customers.find(x=>x.id===r.customerId),v=state.vehicles.find(x=>x.id===r.vehicleId);return(filter==='todos'||r.status===filter)&&`${c?.name} ${vehicleLabel(v)} ${v?.plate} ${r.status}`.toLowerCase().includes(deferred.toLowerCase())}),[state,filter,deferred])
  const open=(r:Rental)=>{setError('');setEditing(r)}
  const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);const vehicleId=String(f.get('vehicleId')),customerId=String(f.get('customerId')),amount=Number(f.get('agreedPrice')),nextPaymentDate=String(f.get('nextPaymentDate'))||undefined;if(!vehicleId||!customerId){setError('Selecciona un cliente y un vehículo.');return}if(!amount||amount<=0){setError('El precio acordado debe ser superior a 0 €.');return}const item:Rental={id:editing?.id||uid('r'),vehicleId,customerId,startDate:String(f.get('startDate')),endDate:String(f.get('endDate'))||undefined,agreedPrice:amount,pricePeriod:String(f.get('pricePeriod')) as PricePeriod,expectedKilometers:Number(f.get('expectedKilometers'))||0,nextPaymentDate,status:String(f.get('status')) as RentalStatus,notes:String(f.get('notes')).trim()};upsert('rentals',item);if(!editing?.id&&item.nextPaymentDate)upsert('payments',{id:uid('p'),rentalId:item.id,dueDate:item.nextPaymentDate,amount:item.agreedPrice,status:'pendiente',method:'',notes:''});const vehicle=state.vehicles.find(v=>v.id===vehicleId);if(vehicle)upsert('vehicles',{...vehicle,status:item.status==='activo'?'alquilado':item.status==='pendiente'?'reservado':'disponible'});setEditing(null)}
  const finalize=(r:Rental)=>{upsert('rentals',{...r,status:'finalizado',endDate:new Date().toISOString().slice(0,10)});const vehicle=state.vehicles.find(v=>v.id===r.vehicleId);if(vehicle)upsert('vehicles',{...vehicle,status:'disponible'})}
  const canCreate=state.vehicles.length>0&&state.customers.length>0
  return <div className="fade-up"><PageHeader eyebrow="Contratos" title="Alquileres" description="Gestiona alquileres por días, semanas, meses o periodos personalizados." action={<button className="btn-primary" disabled={!canCreate} onClick={()=>open(blank())}><Plus size={18}/> Crear alquiler</button>}/>
    {state.rentals.length>0&&<><div className="mb-3 flex flex-wrap gap-2">{[['todos','Todos'],['activo','Activos'],['pendiente','Pendientes'],['finalizado','Finalizados'],['cancelado','Cancelados']].map(([value,label])=><button key={value} onClick={()=>setFilter(value)} className={`min-h-10 cursor-pointer rounded-xl px-4 text-sm font-bold ${filter===value?'bg-brand-500 text-white':'border border-orange-100 bg-white text-stone-600'}`}>{label}</button>)}</div><label className="group relative mb-5 block max-w-2xl"><span className="sr-only">Buscar alquiler</span><input className="field border-orange-200 pr-11" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente, vehículo, matrícula o estado"/>{!query&&<Search className="pointer-events-none absolute right-3.5 top-1/2 -translate-y-1/2 text-brand-500 group-focus-within:hidden" size={18}/>}</label></>}
    <div className="table-shell">{rows.length?<table className="data-table"><thead><tr><th>Alquiler</th><th>Fechas</th><th>Estado</th><th>Próximo pago</th><th>Precio</th><th>Km previstos</th><th>Acciones</th></tr></thead><tbody>{rows.map(r=>{const v=state.vehicles.find(x=>x.id===r.vehicleId),c=state.customers.find(x=>x.id===r.customerId);return <tr key={r.id}><td><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-600"><CalendarRange size={19}/></span><div><p className="font-bold">{vehicleLabel(v)}</p><p className="text-xs text-stone-500">{c?.name} · {v?.plate}</p></div></div></td><td>{date(r.startDate)}<span className="block text-xs text-stone-500">{r.endDate?`hasta ${date(r.endDate)}`:'Sin fecha final'}</span></td><td><Badge tone={tones[r.status]}>{r.status}</Badge></td><td>{r.nextPaymentDate?date(r.nextPaymentDate):'Sin recordatorio'}{r.nextPaymentDate&&<span className="block text-xs text-stone-500">Recurrente mensual</span>}</td><td className="font-bold">{euro.format(r.agreedPrice)}<span className="block text-xs font-normal text-stone-500">/{periods[r.pricePeriod]}</span></td><td>{r.expectedKilometers?r.expectedKilometers.toLocaleString('es-ES'):'Sin estimación'}</td><td><div className="flex items-center gap-4"><button onClick={()=>open(r)} aria-label="Editar alquiler" className="text-stone-500 hover:text-brand-600"><Pencil size={18}/></button>{r.status==='activo'&&<button onClick={()=>finalize(r)} aria-label="Finalizar alquiler" className="text-emerald-700"><CheckCircle2 size={19}/></button>}<ConfirmButton onConfirm={()=>remove('rentals',r.id)}/></div></td></tr>})}</tbody></table>:<EmptyState title="No hay alquileres creados." description={canCreate?'Crea el primer alquiler y elige su periodo.':'Añade primero un vehículo y un cliente.'} action={canCreate?<button className="btn-primary" onClick={()=>open(blank())}><Plus size={18}/> Crear alquiler</button>:undefined}/>}</div>
    {editing&&<Modal title={editing.id?'Editar alquiler':'Crear alquiler'} onClose={()=>setEditing(null)}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2">{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700 sm:col-span-2">{error}</p>}<label><span className="label">Vehículo *</span><select name="vehicleId" className="field" defaultValue={editing.vehicleId} required>{state.vehicles.map(v=><option key={v.id} value={v.id}>{vehicleLabel(v)} · {v.plate}</option>)}</select></label><label><span className="label">Cliente *</span><select name="customerId" className="field" defaultValue={editing.customerId} required>{state.customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span className="label">Tipo de periodo</span><select name="pricePeriod" className="field" defaultValue={editing.pricePeriod}>{Object.entries(periods).map(([value,label])=><option key={value} value={value}>Por {label}</option>)}</select></label><Field label="Precio acordado (€)" name="agreedPrice" type="number" value={editing.agreedPrice} required/><Field label="Fecha de inicio" name="startDate" type="date" value={editing.startDate} required/><Field label="Fecha final (opcional)" name="endDate" type="date" value={editing.endDate||''}/><Field label="Kilómetros previstos" name="expectedKilometers" type="number" value={editing.expectedKilometers}/><label><span className="label">Estado</span><select name="status" className="field" defaultValue={editing.status}>{['activo','pendiente','finalizado','cancelado'].map(value=><option key={value}>{value}</option>)}</select></label><Field label="Próxima fecha de pago (opcional)" name="nextPaymentDate" type="date" value={editing.nextPaymentDate||''}/><p className="self-end rounded-xl bg-brand-50 p-3 text-sm text-stone-600">Si indicas una fecha, el aviso se repetirá cada mes al registrar el cobro.</p><label className="sm:col-span-2"><span className="label">Notas</span><textarea name="notes" className="field min-h-24" defaultValue={editing.notes}/></label><div className="flex gap-3 sm:col-span-2 sm:justify-end"><button type="button" className="btn-secondary" onClick={()=>setEditing(null)}>Cancelar</button><button className="btn-primary">Guardar alquiler</button></div></form></Modal>}
  </div>
}
function Field({label,name,type,value,required=false}:{label:string;name:string;type:string;value:string|number;required?:boolean}){return <label><span className="label">{label}{required&&' *'}</span><input name={name} type={type} className="field" defaultValue={value} required={required}/></label>}
